---
services:

  ## tsdproxy
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxydata:/data
    environment:
      # Get AuthKey from your Tailscale account
      - TSDPROXY_AUTHKEY=tskey-auth-kC43EMqn1a11CNTRL-notarealkey
      # Address of docker server (access to example.com ports)
      - TSDPROXY_HOSTNAME=10.42.37.238
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

  ## PDF
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "pdf"
    ports:
      - 8080:8080

  ## Audiobooks
  abs:
    image: advplyr/audiobookshelf
    container_name: abs
    volumes:
      - /home/zaphod/audiobooks:/audiobooks
      - audiobooks-metadata:/metadata
      - audiobooks-config:/config
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "books"
    ports:
      - 8081:80
    restart: unless-stopped

  ## SearXNG
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "search"
    ports:
      - 8082:8080
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://search.your.domain.com/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  valkey-data2:
  audiobooks-config:
  audiobooks-metadata:
  tsdproxydata: