services:
  karakeep-ts:
    image: tailscale/tailscale:latest
    hostname: karakeep
    environment:
      - TS_AUTHKEY=123
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - ${PWD}/karakeep/config:/config
      - ${PWD}/karakeep/ts-state:/var/lib/tailscale
    restart: unless-stopped
  karakeep-app:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep-app
    restart: unless-stopped
    volumes:
      - ${PWD}/karakeep/data:/data
    network_mode: service:karakeep-ts
    environment:
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - NEXTAUTH_SECRET=123
      - MEILI_MASTER_KEY=123
      - NEXTAUTH_URL=https://karakeep.velociraptor-noodlefish.ts.net
      - DATA_DIR=/data
      - CRAWLER_STORE_SCREENSHOT=true
      - CRAWLER_FULL_PAGE_SCREENSHOT=true
      - CRAWLER_ENABLE_ADBLOCKER=true
      - OPENAI_API_KEY=123
  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    restart: unless-stopped
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=123
    volumes:
      - ${PWD}/karakeep/meilisearch:/meili_data
